In [7]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
b = np.array([[1,2,3], [4,5,6]])

In [7]:
print(a)

[1 2 3]


In [9]:
a.shape

(3,)

In [10]:
b.ndim

2

In [11]:
a[0]

np.int64(1)

In [12]:
a+2

array([3, 4, 5])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [5]:
# Create a NumPy array of shape (3, 4) and multiply each row by its index


new=np.arange(12).reshape(3, 4)
row_indicies = np.arange(3).reshape(3, 1)

result = new*row_indicies

print(result)

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]


In [ ]:
a = np.array([[1],[2],[3]])   #shape (3,1)
b = np.array([10,20,30]) #shape (3,)  -> shape (1,3)

a*b # shape (3,1) * shape (1,3) -> shape (3,3)



array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])