In [7]:
import numpy as np

In [6]:
a = np.array([1, 2, 3])
b = np.array([[1,2,3], [4,5,6]])

In [7]:
print(a)

[1 2 3]


In [9]:
a.shape

(3,)

In [10]:
b.ndim

2

In [11]:
a[0]

np.int64(1)

In [12]:
a+2

array([3, 4, 5])

In [13]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [5]:
# Create a NumPy array of shape (3, 4) and multiply each row by its index


new=np.arange(12).reshape(3, 4)
row_indicies = np.arange(3).reshape(3, 1)

result = new*row_indicies

print(result)

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]


In [ ]:
a = np.array([[1],[2],[3]])   #shape (3,1)
b = np.array([10,20,30]) #shape (3,)  -> shape (1,3)

a*b # shape (3,1) * shape (1,3) -> shape (3,3)



array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [1]:
import time

def download_file(name):
    print(f"{name} started downloading...")
    time.sleep(3)
    print(f"{name} shinished downloading...")

start_time = time.time()

download_file("file1")
download_file("file2")
download_file("file3")

end_time = time.time()

print(f"Total time {end_time - start_time:.2f} seconds")


file1 started downloading...
file1 shinished downloading...
file2 started downloading...
file2 shinished downloading...
file3 started downloading...
file3 shinished downloading...
Total time 9.00 seconds


In [3]:
import threading
import time

def download_file(name):
    print(f"{name} started downloading...")
    time.sleep(3)
    print(f"{name} shinished downloading...")

start_time = time.time()

t1 = threading.Thread(target=download_file, args=("file1",))
t2 = threading.Thread(target=download_file, args=("file2",))
t3 = threading.Thread(target=download_file, args=("file3",))

t1.start()
t2.start()
t3.start()

t1.join()
t2.join()
t3.join()

end_time = time.time()

print(f"Total time {end_time - start_time:.2f} seconds")

file1 started downloading...
file2 started downloading...
file3 started downloading...
file1 shinished downloading...
file3 shinished downloading...
file2 shinished downloading...
Total time 3.01 seconds


In [5]:
import time

def is_prime(n):
    if n<=1:
        return False
    for i in range(2,int(n**2)+1):
        if n%i==0:
            return False
    return True

def count_prime(limit):
    return [x for x in range(limit) if is_prime(x)]

start = time.time()
count_prime(50000)
count_prime(50000)
end = time.time()

print(f"Time taken: {end - start:.2f} seconds")

Time taken: 21.76 seconds


In [10]:
from multiprocessing import Process
import time

def count_primes(limit):
    def is_prime(n):
        if n <= 1:
            return False
        for i in range(2, int(n**0.5) + 1):
            if n % i == 0:
                return False
        return True

    primes = [x for x in range(limit) if is_prime(x)]
    print(f"Found {len(primes)} primes.")

start = time.time()

# Spawn two processes
p1 = Process(target=count_primes, args=(50000,))
p2 = Process(target=count_primes, args=(50000,))

p1.start()
p2.start()

p1.join()
p2.join()

end = time.time()
print(f"Time taken: {end - start:.2f} seconds")


Time taken: 0.09 seconds
